### PR TITLE
Search discourse

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/wisemonk/4)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[config.json, line 10 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-KKkvn1uQ493pohrLvDB:-KKkvn1vQ8zuC7khzG6F:318237796) ([raw file](https://github.com/dgraph-io/wisemonk/blob/902be48b10ec2276a42fad9667b2ee719608a656/config.json#L10)):*
> ```JSON
>                         "maxmsg":20,
>                         "search_over":["Minions","Devs","Users",
>                                 "Blog","Use Cases"],
> ```

Might be better to use their slug instead of their actual visible names. Those names can be changed -- but the slug remains the same.

---

*[main.go, line 391 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-KKkwB57w_tF2b0nX09a:-KKkwB57w_tF2b0nX09b:1415483205) ([raw file](https://github.com/dgraph-io/wisemonk/blob/902be48b10ec2276a42fad9667b2ee719608a656/main.go#L391)):*
> ```Go
> 
> 	if d < 0 {
> 		return "Sorry, going back in time is not what I can do."
> ```

:joy: 

---

*[main.go, line 433 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-KKkwOzQDujDo2F6ULwB:-KKkwOzQDujDo2F6ULwC:1417728113) ([raw file](https://github.com/dgraph-io/wisemonk/blob/902be48b10ec2276a42fad9667b2ee719608a656/main.go#L433)):*
> ```Go
> 		keep := false
> 		for _, cat := range c.SearchOver {
> 			keep = false
> ```

This is unnecessary.

---

*[main.go, line 591 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-KKkxY7MipFGStInZIlD:-KKkxY7NMRDBrQOVE7tC:-435234273) ([raw file](https://github.com/dgraph-io/wisemonk/blob/902be48b10ec2276a42fad9667b2ee719608a656/main.go#L591)):*
> ```Go
> // Checks if the discourse Category supplied as flag exists. If not
> // it logs error and exits.
> func checkDiscourseCategory(channels map[string]*Counter, url string) {
> ```

Shouldn't this be called categories, instead of channels?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4)*

**Comment by pawanrawal** [comment]
Spent time finding how could I make the number of topics optional. This involved having an optional value for the capturing group in the regex. Couldn't figure it out. Maybe will take a stab at it later.

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[config.json, line 10 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-KKkvn1uQ493pohrLvDB:-KKl3xBgI4Y2ESQZdkG6:778570693) ([raw file](https://github.com/dgraph-io/wisemonk/blob/902be48b10ec2276a42fad9667b2ee719608a656/config.json#L10)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Might be better to use their slug instead of their actual visible names. Those names can be changed -- but the slug remains the same.
</details>
Good idea. Done.

---

*[main.go, line 433 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-KKkwOzQDujDo2F6ULwB:-KKl3zm1OpFFHHwZRPYW:-692306159) ([raw file](https://github.com/dgraph-io/wisemonk/blob/902be48b10ec2276a42fad9667b2ee719608a656/main.go#L433)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This is unnecessary.
</details>
yeah, my bad.

---

*[main.go, line 591 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-KKkxY7MipFGStInZIlD:-KKl40hb_3cHAJ-5Yn9s:-780800217) ([raw file](https://github.com/dgraph-io/wisemonk/blob/902be48b10ec2276a42fad9667b2ee719608a656/main.go#L591)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Shouldn't this be called categories, instead of channels?
</details>
The map has its key as a slack channel id. Each Counter then has a `create_topic_in` category and `search_over` category.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-:-KKlPHmq0K7Www4dy2MG:983688646)*

**Comment by manishrjain** [comment]
Maybe just make it so that every line should have a number at the end. Also, instead of silently failing, fail with a usage.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-:-KKlS-DGl2QZIhjPuVz_:821119304)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/wisemonk/4#-:-KKqihloNfcr7NM-PMJz:1417088721)*

**Comment by pawanrawal** [comment]
Merged!

**Pull request closed without merging**
